[build]
  publish = "."

# Enable Netlify form handling without a backend
[build.environment]
  NETLIFY_NODE_VERSION = "20"

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

# Custom 404 page
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404